version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./Mysql/fundme.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_PASSWD}
      MYSQL_DATABASE: fundme
      MYSQL_USER: fundme
      MYSQL_PASSWORD: ${mysql_PASSWD}
    ports:
     - 3306:3306
  web:
    image: nginx:latest
    ports:
      - "7000:80"
    volumes:
      - ./Script:/fund-impact
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: civisblockchain/php-mysql:0.1.0
    volumes:
      - ./Script:/fund-impact

volumes:
  db_data: {}
